### ISSUE TITLE
The userscript doesn't work.

### ISSUE THREAD

**Issue by Alluseri** [Xenorio/YTShareAntiTrack#1]
The userscript doesn't work because you're using a MutationObserver with the prop `subtree`, which is not guaranteed(**at least** on my browser) to be notified of all subtree changes, and, as a matter of fact, it doesn't get notified of the element you're looking for. I'd suggest using intervals like [here](https://github.com/Alluseri/SeriStyle/blob/main/scripts/transformer-general.js#L39).

Extension: Tampermonkey
Browser: Opera GX

**Comment by xenorio** [comment]
Love it when browsers don't adhere to standards. Works perfectly fine on Firefox... Anyway, fixed in https://github.com/Xenorio/YTShareAntiTrack/commit/1c71cfae8330610fde55c3f676047fc349182523 ❤️
