### ISSUE TITLE
Breaks playlist URLs

### ISSUE THREAD

**Issue by zeozeozeo** [Xenorio/YTShareAntiTrack#4]
Playlist URLs look like this: `https://youtube.com/playlist?list=somerandomletters&si=trackingstuff`

This script makes them look like this:

![image](https://github.com/Xenorio/YTShareAntiTrack/assets/108888572/4d38b9df-2025-486e-8bcd-333a20a2518d)

To replicate, just click the share button on any playlist. A possible solution would be only to remove the `&si=*` part if it is a playlist link.

**Comment by xenorio** [comment]
Whoops, didn't even know there was a share button there until now 😅

Fixed in https://github.com/Xenorio/YTShareAntiTrack/commit/1f16330e253391a2dd904cbce9e724a9d15e8348 by whitelisting the "list" parameter
